module.exports = {
  nav:{
    lang: 'English',
    home: 'Home',
    games: 'GAMES',
    hashGame: 'HASH GAME',
    sports: 'SPORTS',
    eSports: 'E-SPORTS',
    casino: 'Casino-Live',
    slots: 'Slots',
    poker: 'Poker',
    nfts: 'NFTs',
    earn: 'Pools',
    dashboard: 'NFT staking pool',
    nftStack: 'Banker pool',
    pools: 'Bet to earn pool',
    betMining: 'Liquidity pool',
    farm: 'FARM',
    dao: 'DAO',
    docs: 'DOCS',
    deck: 'PitchDeck',
    docsDeck: 'DOCS-DECK',
    litepaper: 'Litepaper',
    whitepaper: 'Whitepaper',
    howToPlay: 'How to play',
    login: 'Log in'
  },
  home: {
    bannerTitle1: "BETTIING ",
    bannerTitle2: "FOR WEB3.0",
    bannerTitle3: "Decentralized crypto betting platform",
    bannerText: "All games are provably fair games. Betting and rewards is protected by smart contract. \nThe system of Betting mining and Play to earn will share the profits of the platform with all of users. \n DAO governance make users to become owners .",
    bannerBtn1: "Go to Play",
    bannerBtn2: "Whitepaper",
    aboutTitle1: "About us",
    aboutTitle2: "What is FuniBet?",
    aboutText: "FuniBet is a Web3.0 comprehensive betting platform that provides a full range of online gambling game content.We not only provide users with absolutely fair, open and secure games through blockchain technology. At the same time, we have integrated Web3.0 operating mechanisms such as NFT, De-Fi, GameFi, and SocialFi to bring more benefits to users. Provide higher added value for users' entertainment betting behavior.",
    aboutBtn: "Join Discord",
    aboutRightTitle1: "Games",
    aboutRightTitle2: "Safer & More Credible",
    aboutRightTitle3: "More Fair& More Public",
    aboutRightText1: "FuniBet will provide all kinds of casino, gambling and betting content that you can know in the traditional Web2.0 market, including but not limited to the following products:",
    aboutRightText2: "● Hash game ● Sports & E-Sports ● Casino live ● Slots ●  Poker",
    aboutRightText3: "The user's betting behavior and winning or losing results will be completed through smart contracts, eliminating the doubts of traditional Web2.0 users' distrust of the betting platform.",
    aboutRightText4: "Ac, bibendum duis gravida nullam. At amet nibh platea nibh interdum non, egestas bibendum iaculis. Etiam tristique ultricies tristique ullamcorper donec eget odio ut.",
    gameTitle1: "SOCCER BETTING",
    gameTitle2: "BASKETBALL BETTING",
    gameTitle3: "BASEBALL BETTING",
    gameTitle4: "FOOTBALL BETTING",
    gameTitle5: "TENNIS BETTING",
    gameTitle6: "CS-GO BETTING",
    gameTitle7: "DOTA2 BETTING",
    gameTitle8: "BOXING BETTING",
    gameTitle9: "EYE OF CLEAOPATRA",
    gameTitle10: "RISE SAMURAI",
    gameTitle11: "NORTH GRADIANS",
    gameTitle12: "ROMANCE OF 3KINGDOMS",
    gameTitle13: "BACCARAT",
    gameTitle14: "SPEED ROULETTE",
    gameTitle15: "BLACK JACK",
    gameTitle16: "TEXAS POKER",
    roadmapTitle1: "ROADMAP",
    roadmapTitle2: "TIMELINE",
    roadmapTitle3: "Q2 2023",
    roadmapTitle4: "Q4 2022",
    roadmapTitle5: "Q2 2022",
    roadmapTitle6: "Q1 2023",
    roadmapTitle7: "Q3 2022",
    roadmapTitle8: "Q1 2022",
    roadmapText1: "Listing top 5 crypto exchange",
    roadmapText2: "Fiat onramp to purchase tokens ",
    roadmapText3: "Marketplace is open to other users",
    roadmapText4: "Obtain Philippines gaming license",
    roadmapText5: "Complete development of FuniBet ",
    roadmapText6: "Complete with Games",
    roadmapText7: "NFT staking mining pool",
    roadmapText8: "Banker liquidity  mining pool",
    roadmapText9: "Launch betting  mining pool",
    roadmapText10: "website & social media channels",
    roadmapText11: "Token sale platform & dashboard",
    roadmapText12: "Complete the core team building",
    roadmapText13: "Launch website & dashboard",
    roadmapText14: "Complete security audit on FuniBet ",
    roadmapText15: "Obtain Curacao gaming license",
    roadmapText16: "Develop IOS & Android App ",
    roadmapText17: "Launch BGT staking mining pool",
    roadmapText18: "Start seed round",
    roadmapText19: "Start whitelist pre-sale",
    roadmapText20: "Token list on PancakeSwap",
    roadmapText21: "Start selling NFTs",
    roadmapText22: "Build a team",
    roadmapText23: "Registering a Curacao Corporate Entity",
    roadmapText24: "Development of the hash game",
    roadmapText25: "Development of platform",
    earnTtile1: "How to Earn",
    earnTtile2: "PLAY TO EARN + BET TO EARN",
    earnTtile3: "GAMEFI + DEFI + CASINOFI + SOCIALFI",
    earnTtile4: "Buy NFT -FuniCard",
    earnTtile5: "Staking NFT",
    earnTtile6: "Earn eUSGT every day",
    earnTtile7: "Win USGT by betting",
    earnText1: "Users can buy FuniCards  in FuniBet  NFT marketplace or in third-party NFT marketplace Opensea or Binance.",
    earnText2: "You can stake your NFT in the staking pool, and you will get eUSGT rewards according to the staking time.",
    earnText3: "When you stake your Funi card, your token(eUSGT) earnings per 5 minute",
    earnText4: "You can use eUSGT to win USGT by betting in the game.If you lose you will lose your eUSGT,if you win you will get the real USGT.",
    nftTitle1: "NFTs",
    nftTitle2: "FuniCard",
    nftText1: "FuniCard is the first set of NFTs issued by the FuniBet platform. To a certain extent, it is like a real casino VIP card, but its function and value are far greater than the casino VIP card. Through FuniCard, users can earn a steady stream of income from FuniBet's platform profits. FuniCard will make users to become one of the casino owners, not just a VIP.",
    nftText2: "FuniCard",
    nftText3: "FuniCard EPIC",
    nftText4: "Price: ",
    nftText5: "FuniCard",
    nftText6: "FuniCard LEGENDARY",
    nftText7: "FuniCard",
    nftText8: "FuniCard COMMON",
    nftText9: "FuniCard UNCOMMON",
    nftText10: "FuniCard RARE",
    nftBtn: "Get Nfts",
    blogTitle1: "BLOGS",
    blogTitle2: "Lastest News",
    blogText1: "Latest",
    blogText2: "08 Aug 2022",
    blogText3: "What is Funi cardFuni Card is the first set of NFTs issued bythe FuniBet platform.",
    blogText4: "FuniBet Whitelist Opened Recently What is Funi cardFuni Card is the first set of NFTs issued bythe FuniBet platform. In a way, it’s like a real casino VIP card, but its features and value are far greater...",
    blogText5: "Event",
    blogText6: "08 Aug 2022",
    blogText7: "Innovative dark horse funi.bet opens a new era of Web3.0",
    blogText8: "Innovative dark horse funi.bet opens a new era of Web3.0 Many people are unfamiliar with the concept of Web3. Web3 (also known as Web 3.0, also...",
    blogText9: "Activity",
    blogText10: "05 Aug 2022",
    blogText11: "Funibet, a decentralized comprehensive gambling platform, will be launched soon",
    blogText12: "Funibet, a decentralized comprehensive gambling platform, will be launched soon Human beings have obtained great convenience under the...",
    blogBtn: "Explore more",
    partnerTitle1: "PARTNERS",
    partnerTitle2: "Supported By",
    partnerFaqTitle1: "FAQs",
    partnerFaqTitle2: "Looking for answers?",
    partnerFaqQ1: "What is non homogenous token (NFT)?",
    partnerFaqQ2: "How to buy NFT on the BSC chain of the selling platform?",
    partnerFaqQ3: "What if the transfer fails on the wallet page during transfer?",
    partnerFaqQ4: "How to participate in NFT pledge to obtain income?",
    partnerFaqQ5: "Can I buy BSC chains on one platform, and can NFT be sold on another platform?",
    partnerFaqQ6: "Is NFT trading taxable?",
    partnerFaqQ7: "When trading NFT, it will prompt \"gas fee\". Why should I pay it?",
    partnerFaqQ8: "How to get an NFT account?",
    partnerFaqQ9: "How long does it take to recharge NFT and extract NFT?",
    partnerFaqQ10: "What if NFT accidentally loses the transfer?",
    partnerFaqA1: "The full name of NFT is non fungible token, and Chinese is a non homogenous token. The characteristics of NFT are unique, and it is a unique and easy to verify digital asset.",
    partnerFaqA2: "First of all, you need to use a decentralized wallet to connect to the NFT trading platform. You can buy and sell when you find the trading entrance. At the same time, you should also pay attention to whether the gas fee is sufficient",
    partnerFaqA3: "First check whether the gas handling fee of your wallet is sufficient, and then verify whether the transfer address is correct.",
    partnerFaqA4: "According to the pledge rules, you can participate in the pledge by transferring NFT to the corresponding pledge window",
    partnerFaqA5: "It depends on many factors. After purchasing NFT, you can store it in your wallet. If multiple trading platforms support NFT transactions on this platform, you can transfer transactions on other platforms",
    partnerFaqA6: "At present, most NFT trading platforms in the BSC chain are tax exempt",
    partnerFaqA7: "NFT is cast on the blockchain, which requires miners to authenticate and verify transactions. \n\rThis verification requires these miners to solve complex problems, which in turn requires supercomputing power, so it requires gas fees",
    partnerFaqA8: "Use decentralized wallets such as little fox or TP to establish BSC wallet address, and log in and authorize on the login page of the platform's official website",
    partnerFaqA9: "It mainly depends on the gas fee on the chain. Most BSC chains will arrive in about a minute, mainly depending on the transfer speed of the chain.",
    partnerFaqA10: "If it is the same chain transfer 'lost' or stuck in the chain, most of it can be retrieved, such as cross chain transactions, which cannot be retrieved under normal circumstances. \n\rSo check the wallet address when transferring money"
  },
  nftDetail: {
    text1: "PUBLIC LAUNCH",
    text2: "Genesis NFT - ",
    text3: "FuniCard",
    text4: "Limit",
    text5: "Mint fee",
    text6: "16.September.2022",
    text7: "18:00 UTC",
    text8: "MINT",
    text9: "BUY",
    text10: "BUY ON OPENSEA",
    text11: "BUY ON BINANCE",
    text12: "BUY ON BYBIT",
  },
  commingSoon: {
    text1: "Site",
    text2: "UNNDER",
    text3: "CONSTRUCTION",
    text4: "COMING",
    text5: "SOON",
    text6: "Days",
    text7: "Hours",
    text8: "Minutes",
    text9: "Seconds",
    text10: "Your Email Address",
    text11: "Sign Up",
  },
  view404: {
    text1: "We can’t find the page that you’re looking for.",
    text2: "Back To Homepage",
  },
  footer: {
    title1: "Our Platforms",
    title2: "FuniBet",
    title3: "About us",
    title4: "Stay in touch",
    text1: "Join our community of sporting fanatics, crypto enthusiasts and gamblers",
    text2: "FuniBet",
    text3: "BeingFi",
    text4: "BeDAO",
    text5: "NFT Marketplac",
    text6: "How to earn",
    text7: "NFTs",
    text8: "Games",
    text9: "Whitepaper",
    text10: "Investor Deck",
    text11: "News",
    text12: "About us",
    text13: "Industry",
    text14: "Roadmap",
    text15: "Partner",
    text16: "FAQs",
    text17: "Affiliate",
    btn: "Join Discord"
  }
}
